### ISSUE TITLE
TypeError: iteration over a 0-d tensor

### ISSUE THREAD

**Issue by az5872** [yufengm/SelfAttentive#8]
```
Training data loaded.....
Start training...
# of Epochs: 30
Traceback (most recent call last):
  File "train.py", line 195, in <module>
    all_losses.append( train( lr, epoch )[0] )
  File "train.py", line 112, in train
    hidden = repackage_hidden( hidden )
  File "E:\WORK\SelfAttentive-master\Utility.py", line 25, in repackage_hidden
    return tuple( repackage_hidden( v ) for v in h )
  File "E:\WORK\SelfAttentive-master\Utility.py", line 25, in <genexpr>
    return tuple( repackage_hidden( v ) for v in h )
  File "E:\WORK\SelfAttentive-master\Utility.py", line 25, in repackage_hidden
    return tuple( repackage_hidden( v ) for v in h )
  File "E:\WORK\SelfAttentive-master\Utility.py", line 25, in <genexpr>
    return tuple( repackage_hidden( v ) for v in h )
  File "E:\WORK\SelfAttentive-master\Utility.py", line 25, in repackage_hidden
    return tuple( repackage_hidden( v ) for v in h )
  File "E:\WORK\SelfAttentive-master\Utility.py", line 25, in <genexpr>
    return tuple( repackage_hidden( v ) for v in h )
  File "E:\WORK\SelfAttentive-master\Utility.py", line 25, in repackage_hidden
    return tuple( repackage_hidden( v ) for v in h )
  File "E:\WORK\SelfAttentive-master\Utility.py", line 25, in <genexpr>
    return tuple( repackage_hidden( v ) for v in h )
  File "E:\WORK\SelfAttentive-master\Utility.py", line 25, in repackage_hidden
    return tuple( repackage_hidden( v ) for v in h )
  File "d:\Users\Matt\Anaconda3\lib\site-packages\torch\tensor.py", line 422, in __iter__
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor
```

**Comment by az5872** [comment]
how to solve it?

**Comment by youngkuan** [comment]
this is the problem about pytorch version, you can try replace `# if type( h ) == Variable:` to ` if isinstance(h,Variable):` to solve it. 
```
def repackage_hidden( h ):
    """Wraps hidden states in new Variables, to detach them from their history."""
    # if type( h ) == Variable:
    if isinstance(h,Variable):
        return Variable( h.data )
    else:
        return tuple( repackage_hidden( v ) for v in h )
```
